spring:
  profiles:
    active: local

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

auth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    grant_type: ${KAKAO_GRANT_TYPE}
    token_uri: ${KAKAO_TOKEN_URI}
    user_info_uri: ${KAKAO_USER_INFO_URI}

openai:
  model: ${OPENAI_MODEL}
  secret-key: ${OPENAI_SECRET_KEY}
  chat-completions-url: ${OPENAI_CHAT_COMPLETIONS_URL}