spring:
  profiles:
    active: local

auth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    grant_type: ${KAKAO_GRANT_TYPE}
    token_uri: ${KAKAO_TOKEN_URI}
    user_info_uri: ${KAKAO_USER_INFO_URI}
