spring:
  profiles:
    active: local

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
    header: ${ACCESS_HEAD}
  refresh:
    expiration: ${REFRESH_EXP}
    header: ${REFRESH_HEAD}

auth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    grant_type: ${KAKAO_GRANT_TYPE}
    token_uri: ${KAKAO_TOKEN_URI}
    user_info_uri: ${KAKAO_USER_INFO_URI}
