server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, metrics, prometheus
  endpoint:
    gateway:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

security:
  key: ${ADMIN_KEY}