server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: http://user:8080
          predicates:
            - Path=/users/**
        - id: chat-service
          uri: http://chat:8080
          predicates:
            - Path=/chats/**



